sentence = input("Enter a sentence: ")
old_word = input("Enter the word which you want to  replace: ")
new_word = input("Enter the new word: ")
modified_sentence = sentence.replace(old_word, new_word)
print(modified_sentence)